.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH grex-help 1  "grex-help " 
.SH NAME
grex\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBgrex\-help\fR [\fICOMMAND\fR] 
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
.SH OPTIONS
.TP
[\fICOMMAND\fR]
Subcommand whose help page to print
