.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH grex-run 1  "grex-run " 
.SH NAME
grex\-run \- Run a named action across packs
.SH SYNOPSIS
\fBgrex\-run\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIACTION\fR> 
.SH DESCRIPTION
Run a named action across packs
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIACTION\fR>
Action name to run
