.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH grex-rm 1  "grex-rm " 
.SH NAME
grex\-rm \- Teardown and remove a pack
.SH SYNOPSIS
\fBgrex\-rm\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPATH\fR> 
.SH DESCRIPTION
Teardown and remove a pack
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATH\fR>
Local path of the pack to remove
