.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH grex-exec 1  "grex-exec " 
.SH NAME
grex\-exec \- Execute a shell command in pack context
.SH SYNOPSIS
\fBgrex\-exec\fR [\fB\-h\fR|\fB\-\-help\fR] [\fICMD\fR] 
.SH DESCRIPTION
Execute a shell command in pack context
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fICMD\fR]
Shell command and args to execute
