.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH grex-ls 1  "grex-ls "
.SH NAME
grex\-ls \- List registered packs
.SH SYNOPSIS
\fBgrex\-ls\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPACK_ROOT\fR]
.SH DESCRIPTION
List registered packs
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPACK_ROOT\fR]
Pack root. Directory holding `.grex/pack.yaml`, or the YAML file itself. Defaults to the current working directory. Pass `.` to substitute the current working directory explicitly (v1.3.3 B3)
