.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH grex-update 1  "grex-update " 
.SH NAME
grex\-update \- Sync plus re\-run install on lock change
.SH SYNOPSIS
\fBgrex\-update\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPACK\fR] 
.SH DESCRIPTION
Sync plus re\-run install on lock change
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPACK\fR]
Optional pack path; if omitted, update all
