.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH grex-add 1  "grex-add " 
.SH NAME
grex\-add \- Register and clone a pack
.SH SYNOPSIS
\fBgrex\-add\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIURL\fR> [\fIPATH\fR] 
.SH DESCRIPTION
Register and clone a pack
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIURL\fR>
Git URL of the pack repo
.TP
[\fIPATH\fR]
Optional local path (defaults to repo name)
